//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

pub use super::contacts::Entity as Contacts;
pub use super::project_columns::Entity as ProjectColumns;
pub use super::project_tables::Entity as ProjectTables;
pub use super::projects::Entity as Projects;
pub use super::users::Entity as Users;
